[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "invalid-name",
    "unused-argument",
    "unused-variable",
    "ungrouped-imports"
]

[tool.black]
line-length = 120
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true
