[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "invalid-name",
    "unused-argument",
    "unused-variable",
    "ungrouped-imports",
    "too-many-function-args",
    "redefined-outer-name",
    "unused-import",
    "global-variable-not-assigned",
    "line-too-long",
    "import-error",
    "logging-fstring-interpolation",
    "logging-too-many-args",
    "missing-class-docstring",
    "too-few-public-methods",
    "consider-using-sys-exit"

]

[tool.black]
line-length = 120
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true
