[tool.pylint.messages_control]
disable = [
    "missing-function-docstring",
    "missing-module-docstring",
    "invalid-name",
    "unused-import",
    "redefined-outer-name",
    "logging-fstring-interpolation",
    "line-too-long",
    "import-error",
    "missing-class-docstring",
    "logging-too-many-args",
    "too-few-public-methods",
    "global-variable-not-assigned",
    "consider-using-sys-exit"
]
